using DocumenterInterLinks
using Documenter
using Test

include("run_makedocs.jl")


@testset "Integration Test" begin

    # We build the documentation of DocumenterInterLinks itself as a test

    links = InterLinks(
        "Documenter" => (
            "https://documenter.juliadocs.org/stable/",
            joinpath(@__DIR__, "..", "docs", "src", "inventories", "Documenter.toml")
        ),
        "Julia" => (
            "https://docs.julialang.org/en/v1/",
            joinpath(@__DIR__, "..", "docs", "src", "inventories", "Julia.toml")
        ),
        "DocInventories" => (
            "https://github.com/JuliaDocs/DocInventories.jl/",
            joinpath(@__DIR__, "..", "docs", "src", "inventories", "DocInventories.toml")
        ),
        "sphinx" => "https://www.sphinx-doc.org/en/master/",
        "sphobjinv" => "https://sphobjinv.readthedocs.io/en/stable/",
        "matplotlib" => "https://matplotlib.org/3.7.3/",
    )

    run_makedocs(
        joinpath(@__DIR__, "..", "docs");
        sitename="DocumenterInterLinks.jl",
        plugins=[links],
        format=Documenter.HTML(;
            prettyurls = true,
            canonical  = "https://juliadocs.github.io/DocumenterInterLinks.jl",
            footer     = "Generated by Test",
            edit_link  = "",
            repolink   = ""
        ),
        pages=["Home" => "index.md", "Internals" => "internals.md",],
        check_success=true
    ) do dir, result, success, backtrace, output

        @test success

    end

end
